#!/usr/bin/env bash

day=$1
shift
if hash rund 2>/dev/null; then
    rund $@ -preview=dip25 -preview=dip1000 -preview=dip1008 -version=$day challenges/$day.d
else
    rdmd $@ -preview=dip25 -preview=dip1000 -preview=dip1008 -version=$day challenges/$day.d
fi
